name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: kernel
        run: uname -a

      - name: IMDS
        run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01"

      - name: apt 
        run: sudo apt-get update -y && sudo apt-get upgrade -y

      - name: cloud info
        run: cat /etc/cloud/build.info
